paypal:
  api:
    username: 'xxx_xxx_apix.xxx.com'
    password: 'xxxxxxxxxx'
    signature: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
  email: 'custX_xxxxxxxxxx_per@xxxxxxxx.com'
  visa_account_no: 'xxxxxxxxxxxxxxxx'
  visa_expirey: 'mmyyyy'
mode: 'climber'
